### ISSUE TITLE
Split auth and project type into separate apps within this project

### ISSUE THREAD

**Issue by Treblesteph** [OpenHumans/oh-data-demo-template#15]
so filesystem would be like:

- **oh-demo-template-proj** (project container)
     - .env
     - manage.py
     - Pipfile
     - Pipfile.lock
     - Procfile
     - **demotemplate** (project package)
          - \_\_init__.py
          - settings.py
          - urls.py
          - wsgi.py
     - **ohauth** (oh auth app)
          - **migrations**
               - \_\_init__.py
               - 0001_initial.py
          - **templates**
               - **datauploader**
                    - page.html
          - \_\_init__.py
          - apps.py
          - celery.py
          - models.py
          - tasks.py
          - tests.py
          - urls.py
          - views.py
     - **datauploader** (uploader demo app)
          - **migrations**
               - \_\_init__.py
               - 0001_initial.py
          - **templates**
               - **datauploader**
                    - page.html
          - \_\_init__.py
          - apps.py
          - celery.py
          - models.py
          - tasks.py
          - tests.py
          - urls.py
          - views.py
     - **datadownloader** (downloader demo app)
          - **migrations**
               - \_\_init__.py
               - 0001_initial.py
          - **templates**
               - **datauploader**
                    - page.html
          - \_\_init__.py
          - apps.py
          - celery.py
          - models.py
          - tasks.py
          - tests.py
          - urls.py
          - views.py

**Comment by Treblesteph** [comment]
possible split would involve the following apps:
- `open_humans` for oh auth (already written by mad)
- `main` (containing the following in `views.py`)
  - `index`
  - `complete`
  - `oh_code_to_member`
  - `oh_get_member_data`
- `uploader` (containing the following in `views.py` but currently in `tasks.py`)
  - `xfer_to_open_humans`
  - `add_data_to_open_humans`
  - `make_ex_data_file`
  - `delete_oh_file_by_name`
  - `upload_file_to_oh`
- `downloader` (containing the following steps, but not written yet)
  - select oh project to download from
  - transfer data from open humans
  - do something to this data (checks/visualisation/analysis)

**Comment by manaswinidas** [comment]
Which one should be implemented? First one or last one?

**Comment by Treblesteph** [comment]
this is almost complete in restructure branch :)
