### ISSUE TITLE
OH_EXCHANGE_TOKEN = OH_API_BASE + '/project/exchange-member/'

### ISSUE THREAD

**Issue by Treblesteph** [OpenHumans/oh-data-demo-template#7]
this variable was set in `tasks.py` but not used anywhere, maybe could be removed since not used, but if needed, should be set in `settings.py`

**Comment by manaswinidas** [comment]
I'm interested. Can I work on this?

**Comment by Treblesteph** [comment]
thanks but I have removed it already- sorry I hadn't closed the issue yet!
